### PR TITLE
Fix for browserify

### PR DESCRIPTION
**Pull request by yangshun**
The `require` used in `pencil-tracer.js` is different from the one defined by browserify. I believe that `require` is similar to RequireJS's. Hence I renamed all `require` calls in `pencil-tracer.js` as `requireOrig`.

Secondly, there's a typo for your aliasing in `package.json`. Refer to the commit diff ~_~.

### CODE REVIEW

**Comment by yangshun** [comment]
Happy Birthday @xinan !

**Comment by xinan** [comment]
Thank you! :heart_eyes:  Didn't see that yesterday lol

**Comment by yangshun** [comment]
You too busy having fun outside :trollface:

**Comment by xinan** [comment]
:trollface: How u know

**Pull request closed without merging**
